### ISSUE TITLE
Error: ffmpeg exited with code 1: Invalid duration during specification for ss: NaN

### ISSUE THREAD

**Issue by whyboris** [boi123212321/porn-manager#120]
Identified that I have 10 videos in my directory but didn't extract any.

`Generating thumbnails...`
```
Error: ffmpeg exited with code 1: Invalid duration during specification for ss: NaN
```

Pointed the app at a different folder and created a new 'collection' (clearing the previous video queue) and it worked well.

I suspect when the app doesn't catch the exception when a video doesn't have a correct duration. Probably very easy to fix -- but I'm not up for creating a PR at this moment.

Awesome app! Keep it up 👍

**Comment by boi123212321** [comment]
Hi thanks for reporting.
I have never come across this bug, probably because it only happens on some bad video files.
When the to-be-processed video file does not have a valid duration, the thumbnail generator will just return an empty array, and all should be fine.
I'll add more detailed error logging to that part in the next version, hopefully that will pin down the issue. Unfortunately, there's no way I can just test it because all my ~200 videos just work.

**Comment by cloudstrife11** [comment]
I have also this problem I dont get it fixed

**Comment by boi123212321** [comment]
I'll look into it shortly.

@cloudstrife11 Is it also giving you the same FFMPEG error? Depending on the video size, the amount of thumbnails you're generating (adjustable in the config.json) and your processor, it takes a couple of seconds for 1 scene (somewhere between 2-10 seconds). The scenes tab will fill up over time, so there's no need to wait for 1000 scenes to process; they'll appear one by one.

**Comment by boi123212321** [comment]
I've added some error treatment in the latest version ->
https://github.com/boi123212321/porn-manager/releases/tag/0.4.3

**Comment by cloudstrife11** [comment]
Nice Thx for fast reply. Yea there are no added scenes over about 30 minutes so I dont think they will come. there where no thmbails generating.

**Comment by boi123212321** [comment]
Thanks so much @cloudstrife11, I think (& hope) i've got the error pinned down and fixed.

https://github.com/boi123212321/porn-manager/releases/tag/0.4.4

**Comment by cloudstrife11** [comment]
also thank you very much for making this program, I tested 0.4.4 it crashed after added 0 new videos. So this version also not adding anything on my pc

**Comment by cloudstrife11** [comment]
Also thank you for making this. I have tested the 0.4.4 it crashes when I add also images. When not adding images path to json it works fine ( thumbnails generating).

**Comment by cloudstrife11** [comment]
Also thank you for this program. When I add a image path to json file it crashes after added 0 videos.
But when not adding a image path. it now created all of my thumbnails.

**Comment by boi123212321** [comment]
Did this happen only for this 1 video file? It might be a somewhat broken one because the error comes directly from FFMPEG, I couldn't figure out what code 69 is supposed to mean though...

**Comment by cloudstrife11** [comment]
Yes this is not a error of the program its the videofile itself the video file is corrupted

**Comment by cloudstrife11** [comment]
Now I have added again the imagepath to json now I am getting this error:

porn:warn Scanning folders... +0ms
  porn:warn Added 0 new videos. +3m
(node:5936) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at Object.<anonymous> (C:\snapshot\porn-manager\build\queue\check.js:79:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\snapshot\porn-manager\build\queue\check.js:5:58)
    at <anonymous>
(node:5936) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5936) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


Is it because I have to much images?

**Comment by boi123212321** [comment]
Can you show me your config.json, or at least the IMAGE_PATHS?

**Comment by cloudstrife11** [comment]
{
 "VIDEO_PATHS": [
  "Y:\\Web"
 ],
 "IMAGE_PATHS": ["Y:\\Web"],
 "SCAN_ON_STARTUP": true,
 "SCAN_INTERVAL": 10800000,
 "LIBRARY_PATH": "C:\\Users\\kipke\\Desktop\\organizer\\releases\\win",
 "FFMPEG_PATH": "C:\\Users\\kipke\\Desktop\\organizer\\releases\\win\\ffmpeg.exe",
 "FFPROBE_PATH": "C:\\Users\\kipke\\Desktop\\organizer\\releases\\win\\ffprobe.exe",
 "GENERATE_THUMBNAILS": true,
 "THUMBNAIL_INTERVAL": 60,
 "PASSWORD": null,
 "PORT": 3000,
 "APPLY_ACTOR_LABELS": true,
 "USE_FUZZY_SEARCH": true,
 "FUZZINESS": 0.25

**Comment by boi123212321** [comment]
Alright, how many images do you have? And how deep does your folder tree go? I might have to change the folder walking algorithm.

**Comment by cloudstrife11** [comment]
My folder tree is ; Y;\Web\folders\Images
I have around 100.000 images Like folders with 1000 images in it from websites like brazzers

**Comment by boi123212321** [comment]
We're dealing with quite some amount of data here;
I have changed the algorithm from recursive to iterative, which *should* help with the maximum call stack size exceeded error, I hope.

https://github.com/boi123212321/porn-manager/releases/tag/0.4.7

**Comment by cloudstrife11** [comment]
No Didint fixed it :(

**Comment by boi123212321** [comment]
Right, the error was in the line below that - should work now
Thanks for all the info you give

https://github.com/boi123212321/porn-manager/releases/tag/0.4.8

**Comment by cloudstrife11** [comment]
Not Working :) It now not even giving an error. It complete crash

**Comment by boi123212321** [comment]
Because the video importing seems to be stable now, i've moved the image library issue.
I'm rewriting the image importing, so hopefully it will work fine on very large imports.

track here https://github.com/boi123212321/porn-manager/issues/128

Feel free to open a new issue, if the video importing has problems again
